# Generated by Django 5.2.9 on 2025-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employer", "Employer"), ("seeker", "Seeker")],
                default="seeker",
                max_length=50,
            ),
        ),
    ]
