# Generated by Django 5.2.9 on 2026-01-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.job"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("REVIEWING", "Reviewing"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("CONTRACT", "Contract"),
                    ("FREELANCE", "Freelance"),
                ],
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "seeker")},
        ),
    ]
